apiVersion: kubeflow.org/v2beta1
kind: MPIJob
metadata:
  name: nccl-test
spec:
  slotsPerWorker: 8
  launcherCreationPolicy: WaitForWorkersReady
  runPolicy:
    cleanPodPolicy: Running
  sshAuthMountPath: /root/.ssh
  mpiReplicaSpecs:
    Launcher:
      replicas: 1
      template:
        metadata:
          labels:
            nccl-test-replica: mpi-launcher
        spec:
          containers:
          - name: mpi-launcher
            image: iad.ocir.io/hpc_limited_availability/nccl-tests:pytorch-25.03-nccl-2.26.6-1
            command: ["bash", "-c"]
            ports:
            - containerPort: 2222
              name: ssh
              protocol: TCP
            args:
              - |
                NUM_GPUS=8
                NUM_HOSTS=$(sed -n '$=' /etc/mpi/hostfile)
                NP=$(($NUM_HOSTS*$NUM_GPUS))
                mpirun --allow-run-as-root \
                  -mca coll ^hcoll  -mca plm_rsh_args "-p 2222" \
                  -mca coll_hcoll_enable 0 \
                  -np $NP -npernode $NUM_GPUS --bind-to numa \
                  -x NCCL_DEBUG=WARN \
                  -x NCCL_IB_SPLIT_DATA_ON_QPS=0 \
                  -x NCCL_IB_QPS_PER_CONNECTION=4 \
                  -x NCCL_IB_GID_INDEX=3 \
                  -x NCCL_IB_HCA==mlx5_0,mlx5_2,mlx5_6,mlx5_8,mlx5_10,mlx5_12,mlx5_14,mlx5_16,mlx5_1,mlx5_3,mlx5_7,mlx5_9,mlx5_11,mlx5_13,mlx5_15,mlx5_17 \
                  -x NCCL_IB_TC=41 \
                  -x NCCL_IB_SL=0 \
                  -x NCCL_IB_TIMEOUT=22 \
                  -x HCOLL_ENABLE_MCAST_ALL=0 \
                  -x UCX_TLS=tcp \
                  -x UCX_NET_DEVICES=eth0 \
                  /workspace/nccl-tests/build/all_reduce_perf -b 1G -f 2 -g 1 -e 4G -c 1
    Worker:
      replicas: 2
      template:
        metadata:
          labels:
            nccl-test-replica: mpi-worker
        spec:
          containers:
          - name: mpi-worker
            image: iad.ocir.io/hpc_limited_availability/nccl-tests:pytorch-25.03-nccl-2.26.6-1
            command:
              - /bin/bash
              - -c
              - mkdir -p /var/run/sshd; /usr/sbin/sshd -D -p 2222;
            ports:
            - containerPort: 2222
              name: ssh
              protocol: TCP
            resources:
              limits:
                nvidia.com/gpu: 8
          tolerations:
          - key: nvidia.com/gpu
            operator: Exists
            effect: NoSchedule
