apiVersion: batch.volcano.sh/v1alpha1
kind: Job
metadata:
  annotations:
  name: rccl-tests-job0
spec:
  minAvailable: 0
  plugins:
    ssh: []
    svc: []
  queue: default
  schedulerName: volcano
  tasks:
  - name: mpimaster
    policies:
    - action: CompleteJob
      event: TaskCompleted
    replicas: 1
    template:
      metadata:
      spec:
        containers:
        - command:
          - /bin/bash
          - -c
          - |
            NUM_GPUS=8
            NUM_HOSTS=$(sed -n '$=' /etc/volcano/mpiworker.host)
            NP=$(($NUM_HOSTS*$NUM_GPUS))
            mpirun \
              -mca coll ^hcoll \
              -mca pml ucx \
              -mca btl ^openib \
              -mca plm_rsh_args '-p 2222' \
              --allow-run-as-root \
              -N 8 \
              -np $NP \
              -hostfile /etc/volcano/mpiworker.host \
              --bind-to numa \
              -x RX_QUEUE_LEN=8192 \
              -x IB_RX_QUEUE_LEN=8192 \
              -x UCX_NET_DEVICES=mlx5_0:1 \
              -x HCOLL_ENABLE_MCAST_ALL=0 \
              -x coll_hcoll_enable=0 \
              -x NCCL_CUMEM_ENABLE=0 \
              -x NCCL_IB_TIMEOUT=22 \
              -x NCCL_IB_SL=0 \
              -x NCCL_IB_TC=41 \
              -x NCCL_IB_GID_INDEX=3 \
              -x NCCL_DEBUG=WARN \
              -x NCCL_IB_QPS_PER_CONNECTION=1 \
              -x NCCL_IB_SPLIT_DATA_ON_QPS=0 \
              -x NCCL_IB_HCA='=mlx5_0,mlx5_2,mlx5_3,mlx5_4,mlx5_5,mlx5_7,mlx5_8,mlx5_9' \
              -x NCCL_PXN_DISABLE=0 \
              -x NCCL_NET_PLUGIN=none \
              -x LD_LIBRARY_PATH \
              /workspace/rccl-tests/build/all_reduce_perf -b 1G -e 16G -f 2 -g 1 -n 50
          ports:
          - { name: mpijob-port, containerPort: 2222, protocol: TCP }
          image: iad.ocir.io/idxzjcdglx2s/rccl-tests:rocm-7.0.2-rccl-2.26.6-ubuntu22.04-102025.1
          imagePullPolicy: Always
          name: mpimaster
          resources:
            limits:
              ephemeral-storage: 32Gi
            requests:
              cpu: 2
              ephemeral-storage: 32Gi
              memory: 2Gi
          securityContext:
            privileged: true
            capabilities:
              add: [IPC_LOCK, SYS_PTRACE]
          volumeMounts:
          - { mountPath: /dev/shm, name: shm }
          workingDir: /workspace
        dnsPolicy: ClusterFirstWithHostNet
        hostNetwork: true
        restartPolicy: OnFailure
        terminationGracePeriodSeconds: 2
        volumes:
        - { name: shm, emptyDir: { medium: Memory, sizeLimit: 128Gi }}
  - minAvailable: 0
    name: mpiworker
    replicas: 2
    template:
      spec:
        containers:
        - command:
          - /bin/bash
          - -c
          - mkdir -p /var/run/sshd; /usr/sbin/sshd -D -p 2222
          ports:
          - { name: mpijob-port, containerPort: 2222, protocol: TCP }
          image: iad.ocir.io/idxzjcdglx2s/rccl-tests:rocm-7.0.2-rccl-2.26.6-ubuntu22.04-102025.1
          imagePullPolicy: Always
          name: mpiworker
          resources:
            limits:
              ephemeral-storage: 32Gi
              amd.com/gpu: 8
            requests:
              cpu: 200
              ephemeral-storage: 32Gi
              memory: 1024Gi
              amd.com/gpu: 8
          securityContext:
            privileged: true
            capabilities:
              add: [IPC_LOCK, SYS_PTRACE]
          volumeMounts:
          - { mountPath: /dev/shm, name: shm }
          workingDir: /workspace
        dnsPolicy: ClusterFirstWithHostNet
        hostNetwork: true
        restartPolicy: OnFailure
        terminationGracePeriodSeconds: 2
        tolerations:
        - { key: amd.com/gpu, operator: Exists }
        volumes:
        - { name: shm, emptyDir: { medium: Memory, sizeLimit: 128Gi }}
