apiVersion: kueue.x-k8s.io/v1beta1
kind: ResourceFlavor
metadata:
  name: bm-gpu-mi300x-8
spec:
  nodeLabels:
    node.kubernetes.io/instance-type: BM.GPU.MI300X.8
    amd.com/gpu: "true"
---
apiVersion: kueue.x-k8s.io/v1beta1
kind: ClusterQueue
metadata:
  name: bm-gpu-mi300x-8-rccl-tests-queue
spec:
  namespaceSelector: {}
  resourceGroups:
  - coveredResources: ["cpu", "memory", "amd.com/gpu", "ephemeral-storage"]
    flavors:
    - name: bm-gpu-mi300x-8
      resources:
      - name: cpu
        nominalQuota: "5000"
      - name: memory
        nominalQuota: "204800Gi"
      - name: amd.com/gpu
        nominalQuota: "1600"
      - name: ephemeral-storage
        nominalQuota: "12800Gi"
---
apiVersion: kueue.x-k8s.io/v1beta1
kind: LocalQueue
metadata:
  name: bm-gpu-mi300x-8-rccl-tests
spec:
  clusterQueue: bm-gpu-mi300x-8-rccl-tests-queue
---
apiVersion: kubeflow.org/v2beta1
kind: MPIJob
metadata:
  name: rccl-tests
  labels:
    kueue.x-k8s.io/queue-name: bm-gpu-mi300x-8-rccl-tests
spec:
  slotsPerWorker: 8
  runPolicy:
    cleanPodPolicy: "Running"
  sshAuthMountPath: /root/.ssh
  mpiReplicaSpecs:
    Launcher:
      replicas: 1
      template:
        metadata:
          labels:
            rccl-tests-replica: mpi-launcher
        spec:
          hostNetwork: true
          dnsPolicy: ClusterFirstWithHostNet
          restartPolicy: OnFailure
          terminationGracePeriodSeconds: 2
          containers:
          - name: mpi-launcher
            image: iad.ocir.io/idxzjcdglx2s/rccl-tests:rocm-7.0.2-rccl-2.26.6-ubuntu22.04-102025.1
            imagePullPolicy: Always
            ports:
            - { name: mpijob-port, containerPort: 2222, protocol: TCP }
            command: ["bash", "-c"]
            args:
            - |
              set -e -o pipefail
              trap 'exit=1' SIGINT
              NUM_GPUS=8
              NUM_HOSTS=$(sed -n '$=' /etc/mpi/hostfile)
              NP=$(($NUM_HOSTS*$NUM_GPUS))
              
              while ! (for host in $(awk '{print $1}' /etc/mpi/hostfile); do
                ssh -o ConnectTimeout=5 -o StrictHostKeyChecking=no -p 2222 $host exit 2>/dev/null || exit 1
              done); do
                echo "Waiting for workers to be ready..."
                sleep 5
              done
              echo "All workers are ready!"
              
              mpirun \
                -mca coll ^hcoll \
                -mca pml ucx \
                -mca btl ^openib \
                -mca plm_rsh_args '-p 2222' \
                --allow-run-as-root \
                -np $NP \
                -npernode $NUM_GPUS \
                --bind-to numa \
                -x RX_QUEUE_LEN=8192 \
                -x IB_RX_QUEUE_LEN=8192 \
                -x UCX_NET_DEVICES=mlx5_0:1 \
                -x HCOLL_ENABLE_MCAST_ALL=0 \
                -x coll_hcoll_enable=0 \
                -x NCCL_CUMEM_ENABLE=0 \
                -x NCCL_IB_TIMEOUT=22 \
                -x NCCL_IB_SL=0 \
                -x NCCL_IB_TC=41 \
                -x NCCL_IB_GID_INDEX=3 \
                -x NCCL_DEBUG=WARN \
                -x NCCL_IB_QPS_PER_CONNECTION=1 \
                -x NCCL_IB_SPLIT_DATA_ON_QPS=0 \
                -x NCCL_IB_HCA='=mlx5_0,mlx5_2,mlx5_3,mlx5_4,mlx5_5,mlx5_7,mlx5_8,mlx5_9' \
                -x NCCL_PXN_DISABLE=0 \
                -x NCCL_NET_PLUGIN=none \
                -x LD_LIBRARY_PATH \
                /workspace/rccl-tests/build/all_reduce_perf -b 1G -e 16G -f 2 -g 1 -n 50
            resources:
              limits:
                ephemeral-storage: 32Gi
              requests:
                cpu: 2
                ephemeral-storage: 32Gi
                memory: 2Gi
            securityContext:
              privileged: true
              capabilities:
                add: [IPC_LOCK, SYS_PTRACE]
            volumeMounts:
            - { mountPath: /dev/shm, name: shm }
            workingDir: /workspace
          volumes:
          - { name: shm, emptyDir: { medium: Memory, sizeLimit: 128Gi }}
    Worker:
      replicas: 2
      template:
        metadata:
          labels:
            rccl-tests-replica: mpi-worker
        spec:
          hostNetwork: true
          dnsPolicy: ClusterFirstWithHostNet
          restartPolicy: OnFailure
          terminationGracePeriodSeconds: 2
          containers:
          - name: mpi-worker
            image: iad.ocir.io/idxzjcdglx2s/rccl-tests:rocm-7.0.2-rccl-2.26.6-ubuntu22.04-102025.1
            imagePullPolicy: Always
            ports:
            - { name: mpijob-port, containerPort: 2222, protocol: TCP }
            command:
            - /bin/bash
            - -c
            - mkdir -p /var/run/sshd; /usr/sbin/sshd -D -p 2222
            resources:
              limits:
                ephemeral-storage: 32Gi
                amd.com/gpu: 8
              requests:
                cpu: 200
                ephemeral-storage: 32Gi
                memory: 1024Gi
                amd.com/gpu: 8
            securityContext:
              privileged: true
              capabilities:
                add: [IPC_LOCK, SYS_PTRACE]
            volumeMounts:
            - { mountPath: /dev/shm, name: shm }
            workingDir: /workspace
          tolerations:
          - { key: amd.com/gpu, operator: Exists }
          volumes:
          - { name: shm, emptyDir: { medium: Memory, sizeLimit: 128Gi }}

